version: "3.2"

services:
  sogebot:
    #build:
     # dockerfile: ./Dockerfile
     # context: .
    image: omurilo/luacomtio-bot:latest
    restart: always
    volumes:
      - $PWD/shared:/app/shared/
      - $PWD/logs:/app/logs/
      - /etc/letsencrypt/live/luacomtio.omurilo.dev:/etc/cert/live/luacomtio.omurilo.dev
      - /etc/letsencrypt/archive/luacomtio.omurilo.dev:/etc/cert/archive/luacomtio.omurilo.dev
    ports:
      #- 80:20000 # change your output port
      - 443:20443
      - 9229:9229 # uncomment to use --inspect port
    env_file:
      - ./.env
    environment:
      # ensure locale exists in container, you may need to install it
      LANG: pt_BR.UTF-8
      NODE_OPTIONS: --max_old_space_size=1024 # uncomment to set max 4GB RAM usage (default 2GB)
      #PROFILER: y # uncomment to enable --inspect
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
